apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/podinfo # base could also be in the app's source code repo
components:
  - app-version
namespace: dev-podinfo
namePrefix: dev-
