apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/podinfo # base could also be in the app's source code repo
components:
  - app-version
namespace: prod-podinfo
namePrefix: prod-

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: podinfo
  patch: |-
    - op: replace
      path: /spec/minReadySeconds
      value: 4
- target:
    kind: Deployment
    name: podinfo
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: podinfo
    spec:
      template:
        spec:
          containers:
          - name: podinfod
            env:
            - name: PODINFO_UI_COLOR
              value: "#800f1c"
